### ISSUE TITLE
global state is magic →  no package level storeService var [test, decoupling]

### ISSUE THREAD

**Issue by azbshiri** [gaia-pipeline/gaia#23]
Don't use package level storeService var

> If all of our constructors and functions take their dependencies explicitly, then we no longer have any use for globals. Instead, we can construct all of our database connections, our loggers, our resource pools, in our func main, so that future readers can very clearly map out a component graph.

https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html

instead we could use something like in a simpler manner:
```
// main.go
package main

import (
	"os"

	"github.com/boltdb/bolt"
	"github.com/gorilla/mux"
)

type BoltDBInstance interface {
	Open(path string, mode os.FileMode, options *bolt.Options) (*bolt.DB, error)
}

type server struct {
	storeDB BoltDBInstance
	router       *mux.Router
}

func main() {
	server := server{}
	storeDB, err := bolt.Open("store.db", 0600, nil)
	if err != nil {
		// do something
	}
	server.storeDB = storeDB
	server.routes()
}
```

```
// routes.go
func (s *server) routes() {
 // define routes
}
```

if you @michelvocks argue with this I can make this happen then testing handlers would be much easier.

**Comment by Skarlso** [comment]
First off that would be nice. Outer dependencies should be injected and a global variables should be avoided if it makes sense.

That said, sometimes they are useful, especially if that variable is a built in function that you want to have control off.

Also, only Sith deal in absolutes. Meaning that post is good, but isn't law. If given a certain construct a package level variable makes sense, then by all means, use it. But if it can be injected, then by all means, inject it.

Also, also nit: `"github.com/boltdb/bolt"` --> deprecated/archived. ;) use `coreos`. Though I'm sure you just wrote something from the top of your head. :)

Also, also, also, your example doesn't show off the point of DI actually since your interface makes it so that the Open returns a `*bolt.DB` instance. What would rather be better is to have a Store interface with an Open which does what it does in itself, without exposing anything relating to the database implementation you would be using. Thus a store agnostic way would be rather to have a Connect, Open, Store, Get, and so on, interface that could be replaced by any implementation making unit testing a pretty lightweight task.

In the example above you'd still have to return a bolt.DB struct in a test even though you shouldn't care what db the underlying thing is. For testing purposes it could be an inmemory SQLite db for example.

**Comment by Skarlso** [comment]
Oh, do you actually mean the store_test stuff?
https://github.com/gaia-pipeline/gaia/blob/master/store/store_test.go#L15 here?
Yeah, I agree. This shouldn't be there.

**Comment by azbshiri** [comment]
I didn't want to show DI and I just wrote a way of removing global state and of course that's another issue. About the service abstraction I wrote that too but I looked though and saw that you used only the db session so I didn't include it 😅

**Comment by threeaccents** [comment]
@Skarlso @azbshiri Are you guys going to move forward with these changes? Also @azbshiri were you thinking of wrapper the handler funcs as methods of the `Server` struct in your example?

Having lets say a storage interface:

```go
type Storage interface {
  AddUser(n *NewUser) (*User, error)
  ...
}
```

Then the server takes a storage interface
```go
type Server struct {
  Storage Storage
}
```

Then we wrap the handler funcs and make them `Server` methods. 
Note: I know you're using echo but for the sake of the example using plain handlers.
```go
func (s *Server) handleAddUser() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Get the payload
                 // create the NewUser struct
                 n := NewUser{
                    ...
                 }
                 
                 s.Storage.AddUser(n)		
	})
}
```

Then you can just create a mock storage service to use for testing

```go
type MockStorage struct{}

func (s *MockStorage) AddUser(n *NewUser) (*User, error) {
   ...
}
```

**Comment by threeaccents** [comment]
@azbshiri Nice let me know if I can help in any way with this.

**Comment by michelvocks** [comment]
Sorry guys but you totally lost me. :smile:

I'm probably totally moronic but, except in the [store_test.go](https://github.com/gaia-pipeline/gaia/blob/master/store/store_test.go#L15) we already do this, right? :sweat_smile:
https://github.com/gaia-pipeline/gaia/blob/master/cmd/gaia/main.go#L99

Actually my main idea was to follow the [standard package layout from Ben Johnson](https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1) but I'm not really if I got  it :laughing:

**Comment by Skarlso** [comment]
For reference sake and for completion I like this approach for DI: https://www.elliotdwright.com/2018/02/27/how-i-structure-some-of-my-projects/

Which is clean and very easy to follow and has lazy initialization. :)

**Comment by azbshiri** [comment]
@michelvocks https://github.com/gaia-pipeline/gaia/blob/master/handlers/handler.go#L47

**Comment by michelvocks** [comment]
Ah I see. You are absolutely right. Sounds like a good idea 🤗 
Would be blessed if someone takes this over.

**Comment by azbshiri** [comment]
I first add tests to this then I begin to refactor.

**Comment by Skarlso** [comment]
@azbshiri https://github.com/gaia-pipeline/gaia/blob/master/pipeline/ticker.go#L26
I just found this and realised what you meant. :) 👍

**Comment by Skarlso** [comment]
Fixed. ;)
