### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by prologic** [gaia-pipeline/gaia#231]
We should probably release a new version? Last release was ~Feb; It's not just good practise; it helps keep interested parties following the project/progress via "Watch Releases" :)

**Comment by michelvocks** [comment]
I agree! 
I'm currently waiting for a review to get #201 merged. I think then we are ready for a new release.

**Comment by prologic** [comment]
Sounds good :D

**Comment by prologic** [comment]
Any thoughts on what a realistic release schedule you can maintain?

**Comment by michelvocks** [comment]
> Any thoughts on what a realistic release schedule you can maintain?

No. This is currently a side-project and even tho we love to work on Gaia we also have other stuff going on (real job, familiy, kids etc.). I would like to release quarterly but that is simply not realistic because of the reasons mentioned above. 

Our current approach is to release when we think it is worth to release a new version.

**Comment by prologic** [comment]
I totally understand! I have often been in the same situation (still am!) with the burden of release management and feeling like it takes too much time to do too often. I recently came across an excellent tool however that helps with a lot of this; [goreleaser](https://goreleaser.com/) it might help you too :)

**Comment by michelvocks** [comment]
We are already using it. Goreleaser is awesome!

**Comment by Skarlso** [comment]
@prologic Release has been dooone! :))) hopefully we'll have a much frequent release process now. :)

Please reopen if necessary.
